# Generated by Django 4.1.5 on 2023-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.ImageField(default='herb Rzeszowa.jpg', upload_to='profile_pics'),
        ),
    ]
