# Generated by Django 4.1.5 on 2023-02-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_organisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='num_of_organisations',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
