# Generated by Django 4.1.5 on 2023-02-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_organisation_num_of_organisations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='num_of_organisations',
        ),
    ]
