version: "3.10"

services:
  app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - /.env
    depends_on:
      - db
  db:
    image: postgres:13
    env_file:
      - /.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
#  celery:
#    restart: always
#    build:
#      context: .
#    command: celery -A open_data worker -l info
#    volumes:
#      - .:/code
#    env_file:
#      - /.env
#    depends_on:
#      - db
#      - redis
#      - app
volumes:
  postgres_data:
