# Generated by Django 4.1.5 on 2023-02-24 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(default='datasets/static/icons/government-building-svgrepo-com.svg', upload_to='datasets/static/icons', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
